name: Benchmark
on: [push]

jobs:
  bench:
    name: Run benchmarks on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@preview
      with:
        path: ~/.cargo/registry
        key: bench-${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@preview
      with:
        path: ~/.cargo/git
        key: bench-${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo local build
      uses: actions/cache@preview
      with:
        path: target/debug
        key: bench-${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust via Rustup
      run: rustup update nightly && rustup default nightly
    - name: Run cargo bench
      run: cargo +nightly bench no_term
