name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust via Rustup
      run: rustup update stable && rustup default stable
    - run: cargo test

  lint:
    name: Rustfmt and Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Toolchain via Rustup
      run: rustup update stable && rustup default stable && rustup component add rustfmt clippy
    - run: cargo fmt -- --check
    - run: cargo clippy
